name: Terracotta
options:
  bundleIdPrefix: site.yinmo
  deploymentTarget:
    iOS: 15.0
targets:
  Terracotta:
    type: application
    platform: iOS
    sources: [Terracotta]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: site.yinmo.terracotta
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_IDENTITY: ""
    entitlements:
      path: Terracotta/Terracotta.entitlements
    info:
      path: Terracotta/Info.plist
    dependencies:
      - target: TerracottaShared
  TerracottaNetworkExtension:
    type: app-extension
    platform: iOS
    extensionPoint: com.apple.networkextension.packet-tunnel
    sources: [TerracottaNetworkExtension]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: site.yinmo.terracotta.TerracottaNetworkExtension
        DEVELOPMENT_TEAM: ""
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_IDENTITY: ""
    entitlements:
      path: TerracottaNetworkExtension/TerracottaNetworkExtension.entitlements
    info:
      path: TerracottaNetworkExtension/Info.plist
    dependencies:
      - target: TerracottaShared
  TerracottaShared:
    type: framework
    platform: iOS
    sources: [TerracottaShared]
    settings:
      base:
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_IDENTITY: ""
